# Generated by Django 4.1.dev20220214074346 on 2022-06-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
    ]
